# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build_and_test:
    docker:
      - image: circleci/golang:1.13

    working_directory: /go/src/github.com/cloudspannerecosystem/harbourbridge

    steps:
      - checkout

      # create a spanner instance
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
      - run: gcloud info
      - run: gcloud config configurations create emulator
      - run: gcloud config set auth/disable_credentials true
      - run: gcloud config set project emulator-test-project
      - run: gcloud config set api_endpoint_overrides/spanner http://localhost:9020/
      - run: gcloud spanner instances create test-instance --config=emulator-config --description="Test Instance" --nodes=1

      # run tests
      - uses: actions/setup-go@v2
        with:
          go-version: "1.13"
      - run: go version
      - run: go test -v ./...
        env:
          SPANNER_EMULATOR_HOST: localhost:9010
          HARBOURBRIDGE_TESTS_GCLOUD_PROJECT_ID: emulator-test-project
          HARBOURBRIDGE_TESTS_GCLOUD_INSTANCE_ID: test-instance

workflows:
  version: 2

  commit: # Run on every commit.
    jobs:
      - build_and_test

  nightly: # Run every night.
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build_and_test
